services:
  - type: web
    name: stuntingpred
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers 1 --bind 0.0.0.0:$PORT --timeout 120 --preload
    envVars:
      - key: SECRET_KEY
        value: stuntingpred-ums-heri2025-lombok-ntb-secret-render
      - key: PORT
        value: 10000
